import { WASI, File, Directory, OpenFile, ConsoleStdout, PreopenDirectory, Inode } from "@bjorn3/browser_wasi_shim";

/**
 * Supported ecosystems for CDD code generation.
 */
export type Ecosystem = 
    | 'cdd-c' | 'cdd-cpp' | 'cdd-csharp' | 'cdd-go' 
    | 'cdd-java' | 'cdd-kotlin' | 'cdd-php' | 'cdd-python' 
    | 'cdd-ruby' | 'cdd-rust' | 'cdd-sh' | 'cdd-swift' | 'cdd-ts';

/**
 * Supported generation targets.
 */
export type Target = 'to_sdk' | 'to_sdk_cli' | 'to_server';

/**
 * Options for generating code from an OpenAPI specification.
 */
export interface GenerateOptions {
    /** The target ecosystem for generation. */
    ecosystem: Ecosystem;
    /** The type of generation (e.g., to_sdk, to_server). */
    target: Target;
    /** The OpenAPI specification content as a string or Uint8Array. */
    specContent: string | Uint8Array;
    /** The WebAssembly binary for the target ecosystem. */
    wasmBinary: Uint8Array | ArrayBuffer;
    /** Optional flag to enable printing WASM stdout to the console. */
    printStdout?: boolean;
    /** Optional additional arguments to pass to the WASM binary. */
    additionalArgs?: string[];
}

/**
 * A file generated by the CDD WASM SDK.
 */
export interface GeneratedFile {
    /** The relative path of the generated file. */
    path: string;
    /** The file contents as a Uint8Array. */
    content: Uint8Array;
}

/**
 * The CDD WebAssembly SDK class for executing generators.
 */
export class CddWasmSdk {
    /**
     * Generates code from an OpenAPI specification using the provided WASM binary.
     * @param options The generation options, including ecosystem, spec content, and WASM binary.
     * @returns A promise that resolves to an array of generated files.
     * @throws An error if the WASM binary is invalid or execution fails.
     */
    static async fromOpenApi(options: GenerateOptions): Promise<GeneratedFile[]> {
        const specData = typeof options.specContent === 'string' 
            ? new TextEncoder().encode(options.specContent)
            : new Uint8Array(options.specContent);

        const specFile = new File(specData);
        const outDir = new Directory(new Map<string, Inode>());
        
        const rootMap = new Map<string, Inode>([
            ["spec.json", specFile],
            ["out", outDir]
        ]);

        const rootPreopen = new PreopenDirectory("/", rootMap);

        const args = [
            options.ecosystem,
            "from_openapi",
            options.target,
            "-i",
            "/spec.json",
            "-o",
            "/out",
            ...(options.additionalArgs || [])
        ];

        const env: string[] = [];
        
        const fds = [
            new OpenFile(new File(new Uint8Array([]))),
            ConsoleStdout.lineBuffered((msg: string) => options.printStdout ? console.log(`[${options.ecosystem}] ${msg}`) : null),
            ConsoleStdout.lineBuffered((msg: string) => console.error(`[${options.ecosystem}] ${msg}`)),
            rootPreopen
        ];

        const wasi = new WASI(args, env, fds);
        

        const buffer = options.wasmBinary instanceof Uint8Array ? options.wasmBinary.buffer : options.wasmBinary;

        if (options.ecosystem === 'cdd-python') {
            // @ts-ignore
            const { loadPyodide } = await import("https://cdn.jsdelivr.net/pyodide/v0.25.0/full/pyodide.mjs");
            const pyodide = await loadPyodide({
                indexURL: "https://cdn.jsdelivr.net/pyodide/v0.25.0/full/"
            });
            await pyodide.loadPackage("micropip");
            const micropip = pyodide.pyimport("micropip");
            await micropip.install(["pydantic", "libcst", "urllib3"]); // and python-cdd... wait python-cdd isn't on pure pure pypi? Or it is, but it might need to be pure python. Let's assume python-cdd is pure python.
            await micropip.install("python-cdd");
            
            // unpack zip
            pyodide.unpackArchive(buffer as ArrayBuffer, "zip", { extractDir: "/cdd_src" });
            
            // mount spec.json
            const specContentStr = typeof options.specContent === 'string' ? options.specContent : new TextDecoder().decode(options.specContent);
            pyodide.FS.writeFile("/spec.json", specContentStr);
            pyodide.FS.mkdir("/out");
            
            const sys = pyodide.pyimport("sys");
            sys.path.append("/cdd_src");
            sys.argv.clear();
            ["cdd-python", "from_openapi", options.target, "-i", "/spec.json", "-o", "/out"].concat(options.additionalArgs || []).forEach(a => sys.argv.append(a));
            
            await pyodide.runPythonAsync(`
                import openapi_client.cli
                try:
                    openapi_client.cli.main()
                except SystemExit as e:
                    if e.code != 0:
                        raise Exception(f"Failed with exit code {e.code}")
            `);
            
            const results: GeneratedFile[] = [];
            function readPyDir(dirPath: string, basePath: string) {
                const names = pyodide.FS.readdir(dirPath).filter((n: string) => n !== '.' && n !== '..');
                for (const name of names) {
                    const fullPath = dirPath + "/" + name;
                    const stat = pyodide.FS.stat(fullPath);
                    const relPath = basePath ? `${basePath}/${name}` : name;
                    if (pyodide.FS.isDir(stat.mode)) {
                        readPyDir(fullPath, relPath);
                    } else {
                        results.push({
                            path: relPath,
                            content: pyodide.FS.readFile(fullPath)
                        });
                    }
                }
            }
            readPyDir("/out", "");
            return results;
        }

        
        
        
        if (options.ecosystem === 'cdd-sh') {
            throw new Error("mvdan-sh execution via ZIP is not yet wired dynamically in this environment.");
        }
        


        if (options.ecosystem === 'cdd-java') {
            throw new Error("CheerpJ execution not yet fully wired in the browser shim environment. Requires cheerpjRunMain with mounted .jar file.");
        }

        
        
        const module = await WebAssembly.compile(buffer as ArrayBuffer);
    

        
        const instance = await WebAssembly.instantiate(module, {
            "wasi_snapshot_preview1": wasi.wasiImport,
        });

        let exitCode = 0;
        try {
            if (!(instance as any).exports._start) {
                throw new Error("WASM binary missing _start export (invalid or dummy WASM)");
            }
            exitCode = wasi.start(instance as any);
        } catch (e: any) {
            if (e && e.name === 'WASIProcExit') {
                exitCode = e.code;
            } else if (e && typeof e.code === 'number') {
                exitCode = e.code;
            } else {
                throw e; // Rethrow actual errors like TypeError
            }
        }

        if (exitCode !== 0) {
            throw new Error(`WASM execution failed with exit code ${exitCode}`);
        }

        const results: GeneratedFile[] = [];
        
        function readDir(dir: Directory, basePath: string) {
            if (!dir.contents) return;

            for (const [name, entry] of dir.contents.entries()) {
                const fullPath = basePath ? `${basePath}/${name}` : name;
                if (entry instanceof File) {
                    results.push({
                        path: fullPath,
                        content: entry.data
                    });
                } else if (entry instanceof Directory) {
                    readDir(entry, fullPath);
                }
            }
        }

        readDir(outDir, "");

        return results;
    }
}
