import { WASI, File, Directory, OpenFile, ConsoleStdout, PreopenDirectory, Inode } from "@bjorn3/browser_wasi_shim";

/**
 * Ecosystem names corresponding to the supported cdd-* modules.
 */
export type Ecosystem = 
    | 'cdd-c' | 'cdd-cpp' | 'cdd-csharp' | 'cdd-go' 
    | 'cdd-java' | 'cdd-kotlin' | 'cdd-php' | 'cdd-python' 
    | 'cdd-ruby' | 'cdd-rust' | 'cdd-swift' | 'cdd-ts';

/**
 * Generation target formats.
 */
export type Target = 'to_sdk' | 'to_sdk_cli' | 'to_server';

/**
 * Options required to generate code using a cdd-* WASM module.
 */
export interface GenerateOptions {
    /** The target ecosystem (e.g., 'cdd-python') */
    ecosystem: Ecosystem;
    /** The target output type */
    target: Target;
    /** The OpenAPI specification content as a string or raw bytes */
    specContent: string | Uint8Array;
    /** The pre-compiled WASM binary */
    wasmBinary: Uint8Array | ArrayBuffer;
    /** If true, the WASM stdout will be piped to console.log */
    printStdout?: boolean;
}

/**
 * A file generated by the cdd-* WASM module.
 */
export interface GeneratedFile {
    /** The relative path of the file */
    path: string;
    /** The file's binary content */
    content: Uint8Array;
}

/**
 * The primary SDK class for interacting with cdd-* WASM modules.
 */
export class CddWasmSdk {
    /**
     * Executes the WASM compilation payload securely within the browser's WASI environment.
     * 
     * @param options The generation options.
     * @returns A promise that resolves to an array of generated files.
     */
    static async fromOpenApi(options: GenerateOptions): Promise<GeneratedFile[]> {
        const specData = typeof options.specContent === 'string' 
            ? new TextEncoder().encode(options.specContent)
            : new Uint8Array(options.specContent);

        // Mount a virtual filesystem
        const specFile = new File(specData);
        const outDir = new Directory(new Map<string, Inode>());
        
        // Define root folder map
        const rootMap = new Map<string, Inode>([
            ["spec.json", specFile],
            ["out", outDir]
        ]);

        const rootPreopen = new PreopenDirectory("/", rootMap);

        const args = [
            options.ecosystem,
            "from_openapi",
            options.target,
            "-i",
            "/spec.json",
            "-o",
            "/out"
        ];

        const env: string[] = [];
        
        // FDs 0, 1, 2 = stdin, stdout, stderr, 3 = / root preopen
        const fds = [
            new OpenFile(new File(new Uint8Array([]))), // stdin
            ConsoleStdout.lineBuffered((msg: string) => options.printStdout ? console.log(`[${options.ecosystem}] ${msg}`) : null), // stdout
            ConsoleStdout.lineBuffered((msg: string) => console.error(`[${options.ecosystem}] ${msg}`)), // stderr
            rootPreopen
        ];

        const wasi = new WASI(args, env, fds);
        
        // Ensure the input buffer is seen correctly
        const buffer = options.wasmBinary instanceof Uint8Array ? options.wasmBinary.buffer : options.wasmBinary;
        const module = await WebAssembly.compile(buffer as ArrayBuffer);
        
        const instance = await WebAssembly.instantiate(module, {
            "wasi_snapshot_preview1": wasi.wasiImport,
        });

        try {
            // Execution blocks until exit() is called or main() finishes
            wasi.start(instance as any);
        } catch (e: any) {
            // browser_wasi_shim typically throws WASI Exit signals as exceptions (Exit(0))
            if (e.code !== 0 && e.code !== undefined) {
                throw new Error(`${options.ecosystem} exited with code ${e.code}`);
            }
        }

        // Recursively extract all generated files from the /out virtual directory
        const results: GeneratedFile[] = [];
        
        function readDir(dir: Directory, basePath: string) {
            if (!dir.contents) return;

            for (const [name, entry] of dir.contents.entries()) {
                const fullPath = basePath ? `${basePath}/${name}` : name;
                if (entry instanceof File) {
                    results.push({
                        path: fullPath,
                        content: entry.data
                    });
                } else if (entry instanceof Directory) {
                    readDir(entry, fullPath);
                }
            }
        }

        readDir(outDir, "");

        return results;
    }
}
