name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always
  DATABASE_URL: postgres://postgres:password@localhost/cdd

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: cdd
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libssl-dev gcc libpq-dev

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Install cargo-tarpaulin
        run: cargo install cargo-tarpaulin

      - name: Setup Database
        run: |
          cargo install diesel_cli --no-default-features --features postgres
          diesel setup --database-url postgres://postgres:password@localhost/cdd
          diesel migration run --database-url postgres://postgres:password@localhost/cdd

      - name: Run checks
        run: cargo check --verbose

      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Run tests & coverage
        run: cargo tarpaulin --verbose --workspace --timeout 120 --out xml

      - name: Build docs
        run: cargo doc --no-deps
